### ISSUE TITLE
Not refresh

### ISSUE THREAD

**Issue by Lazze85** [dannerph/homeassistant-sunnybeam#2]
I create the sensors and read the values ​​but it updates them only if I restart Home Assistant

**Comment by dannerph** [comment]
any logs? errors? Which home assistant version?
Working for me

**Comment by Lazze85** [comment]
Home Assistant 2023.3.1

there are no obvious errors, but I'm not an expert I just followed the guide.
I tried to restart with the USB port disconnected and the values ​​are unknown, if I restart with the USB connected it updates the sensors

**Comment by dannerph** [comment]
Ah I think I now got your point: In my setup, once I disconnect the USB, I need to restart HA in order to get it working again. I have not yet had time to figure out why it is not possible to connect to the USB while running.
Maybe I can convert the setup to the ConfigFlow, in order to allow a relead of the component, that should be feasible without too much effort. Need to see when I find some time for it.

**Comment by Lazze85** [comment]
Thank you

**Comment by dannerph** [comment]
Should be fixed with the new version
